description: foo
name: A job to say hello
runs:
  using: composite
  steps:
    - name: Hello world action step
      id: hello
      uses: actions/hello-world-docker-action@v2
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
