on: workflow_dispatch

jobs:
  fetch:
    uses: actions/checkout@v3

  deploy-1:
    runs-on: ubuntu-latest
    name: job1
    steps:
      - uses: ./.github/actions/main

  deploy-2:
    runs-on: ubuntu-latest
    name: job2
    steps:
      - uses: ./.github/actions/second