# on: workflow_dispatch
on: push

jobs:
  # fetch:
  #   uses: actions/checkout@v3

  deploy-1:
    runs-on: ubuntu-latest
    name: job1
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/main.yaml

  deploy-2:
    runs-on: ubuntu-latest
    name: job2
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/second.yaml