# on: workflow_dispatch
on: push

jobs:
  # fetch:
  #   uses: actions/checkout@v3

  deploy-1:
    runs-on: ubuntu-latest
    steps:
      - name: fetch
        uses: actions/checkout@v3
      - name: main
        uses: ./.github/actions/main

  deploy-2:
    runs-on: ubuntu-latest
    steps:
      - name: fetch
        uses: actions/checkout@v3

      - name: second
        uses: ./.github/actions/second
